Update to FW version 3.0.0
elral/CommunityTemplate pull request #11
Opened 2024-08-29 09:11 UTC by elral

## Description of changes

Once a new version for the core version is released and the open PR's are merged (#3 / #6 / #8 / #10), this version must also be used for this repo.

Changed `custom_core_firmware_version` to `2.5.2`

2024-11-01 12:21 UTC, elral commented
Next FW release will be 3.0 instead of 2.5.2 as original intended

2024-11-01 13:13 UTC, DocMoebiuz requested changes

2025-02-12 12:09 UTC, DocMoebiuz approved these changes

2025-07-30 06:49 UTC, DocMoebiuz approved these changes

2025-07-30 06:50 UTC, DocMoebiuz approved these changes

2025-07-30 07:09 UTC, DocMoebiuz commented
implemented by #12

2025-07-30 07:09 UTC, closed without merging